services:
  - type: web
    name: kmj-erp
    env: node
    buildCommand: mkdir -p /opt/render/.cache/puppeteer && PUPPETEER_SKIP_DOWNLOAD=false PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer npm install && npx puppeteer browsers install chrome-headless-shell && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20.18.0
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
