import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatLensPower, lensTypeLabel } from "./helpers";

export interface DemandPdfItem {
  coating: string;
  lensType: string;
  powerKey: string;
  qty: number;
  current?: number;
  target?: number;
  price?: number;
}

export interface DemandPdfData {
  target?: number;
  generatedAt?: string;
  items: DemandPdfItem[];
}

function formatPower(lensType: string, powerKey: string): string {
  const type = lensTypeLabel(lensType);
  const power = formatLensPower(powerKey);
  return power === "—" ? type : `${type} · ${power}`;
}

export function generateDemandPdf(data: DemandPdfData): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  const indigo: [number, number, number] = [30, 64, 175];
  const gray: [number, number, number] = [107, 114, 128];
  const dark: [number, number, number] = [17, 24, 39];
  const light: [number, number, number] = [249, 250, 251];
  const border: [number, number, number] = [229, 231, 235];

  // Top Header Banner
  doc.setFillColor(...indigo);
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("STOCK DEMAND", margin, 18);

  // Generated Date
  const dateStr = data.generatedAt
    ? new Date(data.generatedAt).toLocaleString("en-IN", {
        day: "2-digit",
        month: "short",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : "—";

  doc.setTextColor(...gray);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Generated On:", margin, 38);
  doc.setTextColor(...dark);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text(dateStr, margin, 45);

  doc.setDrawColor(...border);
  doc.setLineWidth(0.4);
  doc.line(margin, 50, pageWidth - margin, 50);

  const fmtMoney = (n: number): string => `₹${(n || 0).toLocaleString("en-IN")}`;

  // Table Data
  const rows = data.items.map((it) => [
    it.coating || "—",
    formatPower(it.lensType, it.powerKey),
    String(it.current ?? 0),
    String(it.target ?? 0),
    String(it.qty),
    fmtMoney(it.price ?? 0),
    fmtMoney((it.qty || 0) * (it.price ?? 0)),
  ]);

  autoTable(doc, {
    startY: 56,
    margin: { left: margin, right: margin },
    head: [["Coating", "Lens (Type & Power)", "Current", "Target", "To Buy", "Rate", "Amount"]],
    body: rows,
    theme: "grid",
    headStyles: {
      fillColor: indigo,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      cellPadding: 4,
    },
    styles: {
      fontSize: 9,
      textColor: dark,
      cellPadding: 4,
      lineColor: border,
      lineWidth: 0.15,
      valign: "middle",
    },
    alternateRowStyles: { fillColor: light },
    columnStyles: {
      0: { cellWidth: contentWidth * 0.17 },
      1: { cellWidth: contentWidth * 0.28 },
      2: { cellWidth: contentWidth * 0.09, halign: "center" },
      3: { cellWidth: contentWidth * 0.09, halign: "center" },
      4: { cellWidth: contentWidth * 0.1, halign: "center" },
      5: { cellWidth: contentWidth * 0.13, halign: "right" },
      6: { cellWidth: contentWidth * 0.14, halign: "right" },
    },
  });

  const tableEnd = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;
  const totalNeed = data.items.reduce((s, it) => s + it.qty, 0);
  const totalAmount = data.items.reduce((s, it) => s + it.qty * (it.price ?? 0), 0);

  // Totals Box
  const y = tableEnd + 12;
  const totalBoxW = contentWidth * 0.55;
  const totalBoxX = pageWidth - margin - totalBoxW;
  const boxH = 20;

  doc.setFillColor(...light);
  doc.roundedRect(totalBoxX, y, totalBoxW, boxH, 2, 2, "F");
  doc.setDrawColor(...border);
  doc.roundedRect(totalBoxX, y, totalBoxW, boxH, 2, 2, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...indigo);
  doc.text(`Total Pieces To Buy:`, totalBoxX + 6, y + 8);
  doc.text(`Total Amount:`, totalBoxX + 6, y + 16);
  doc.setFontSize(12);
  doc.text(String(totalNeed), totalBoxX + totalBoxW - 6, y + 8, { align: "right" });
  doc.text(fmtMoney(totalAmount), totalBoxX + totalBoxW - 6, y + 16, { align: "right" });

  // Footer
  const footerY = Math.max(y + boxH + 20, pageHeight - 20);
  doc.setDrawColor(...border);
  doc.setLineWidth(0.3);
  doc.line(margin, footerY, pageWidth - margin, footerY);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by KMJ Optical Lens Warehouse", pageWidth / 2, footerY + 6, { align: "center" });

  const dateFile = new Date().toISOString().slice(0, 10);
  doc.save(`Stock_Demand_${dateFile}.pdf`);
}