import { z } from "zod";
import { VALID_GENDERS } from "../types";

export const createVariantSchema = z.object({
  productId: z.string().optional(),
  brandId: z.string().optional(),
  brandName: z.string().optional(),
  category: z.string().optional(),
  model: z.string().optional(),
  gender: z.enum(VALID_GENDERS).optional(),
  sku: z.string().trim().min(1, "SKU is required"),
  color: z.string().optional(),
  size: z.string().optional(),
  material: z.string().optional(),
  frameShape: z.string().optional(),
  frameType: z.string().optional(),
  templeSize: z.string().optional(),
  bridgeSize: z.string().optional(),
  lensWidth: z.string().optional(),
  status: z.string().optional(),
  defaultSellingPrice: z.number().min(0).optional(),
  rackId: z.string().optional(),
  supplierId: z.string().optional(),
  supplierName: z.string().optional(),
  attributes: z.record(z.string(), z.unknown()).optional(),
  image: z.string().optional(),
}).strict();

export const updateVariantSchema = z.object({
  color: z.string().optional(),
  size: z.string().optional(),
  gender: z.enum(VALID_GENDERS).optional(),
  material: z.string().optional(),
  frameShape: z.string().optional(),
  frameType: z.string().optional(),
  templeSize: z.string().optional(),
  bridgeSize: z.string().optional(),
  lensWidth: z.string().optional(),
  status: z.string().optional(),
  defaultSellingPrice: z.number().min(0).optional(),
  rackId: z.string().nullable().optional(),
  supplierId: z.string().optional(),
  supplierName: z.string().optional(),
  attributes: z.record(z.string(), z.unknown()).optional(),
  image: z.string().optional(),
  active: z.boolean().optional(),
}).strict();
